/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eleqstory_db;

import java.sql.Connection;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.logging.Level;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.JFileChooser;
import java.io.File;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.io.FileInputStream;
import java.io.InputStream;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author danil
 */
public class Main_Window extends javax.swing.JFrame {
    
    public String imgPath = null;
    public int position = 0;
    public ButtonGroup bg;

    /**
     * Creates new form Main_Window
     */
    public Main_Window() {
        initComponents();
        
        // create radio buttons group.
        this.bg =  new ButtonGroup();
        this.bg.add(radio_Male);
        this.bg.add(radio_Female);
    }
    
    /*** the own code. ***/
    
    private Connection getConnection() {
        /*** Returns the Connection object or null if there is no connection with the database. ***/
        
        // the data for getting the database connection.
        String url = "jdbc:mysql://localhost/products_db2";
        String username = "root";
        String password = "";
        // declare the Connection variable and initialize it to null.
        Connection con = null;
        try {
            // get the connection with the local database.
            con = DriverManager.getConnection(url, username, password);
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(Level.SEVERE, null, ex);
            // show the other window with the "Not connected" label if there was no connection.
            JOptionPane.showMessageDialog(null, "Not connected!", "Something has gone wrond!", HEIGHT);
        } finally {
            // return the status of the connection as a result.
            return con;
        }
    }
    
    private ImageIcon resizeImg(String imagePath, byte[] pic) {
        /*** gets an image using its path and returns the resized copy of the image for the lbl_image label. ***/
        
        // declare the variable that will conteins the original image. But now it's null.
        ImageIcon myImage = null;
        
        // check if we have the path we could get the image with.
        if (imagePath != null) {
            // if so, get the image using the path.
            myImage = new ImageIcon(imagePath);
        }
        else {
            myImage = new ImageIcon(pic);
        }
        
        // resize the image to the lbl_image label size using an instance of the Image class.
        Image img = myImage.getImage();
        Image img2 = img.getScaledInstance(lbl_image.getWidth(), lbl_image.getHeight(), Image.SCALE_SMOOTH);
        
        // get the new scaled image and store it as an icon.
        ImageIcon image = new ImageIcon(img2);
        
        return image;
    }
    
    private boolean checkOptsInputs() {
        /*** checks if the operations fields aren't empty. ***/    
        
        if (txt_name.getText().isEmpty() || txt_price.getText().isEmpty() ||
            txt_addDate.getText().isEmpty())
                return false;
        else {
            try {
                // try to convert the price to a float value and return true if success.
                Float.parseFloat(txt_price.getText());
                return true;
            }
            catch (NumberFormatException ex) {
                return false;
            }
        }
    }
    
    private boolean checkMbrsInputs() {
        /*** checks if the new member fields aren't empty. ***/
        
        if (txt_mbr_name.getText().isEmpty() || txt_mbr_lastName.getText().isEmpty() ||
            (!radio_Male.isSelected() && !radio_Female.isSelected()))
                return false;
        
        return true;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        JPanel_sideBar = new javax.swing.JPanel();
        JPanel_Basics = new javax.swing.JPanel();
        btn_Guides = new javax.swing.JButton();
        btn_Operations = new javax.swing.JButton();
        btn_Reports = new javax.swing.JButton();
        btn_About = new javax.swing.JButton();
        JPanel_Operations = new javax.swing.JPanel();
        btn_Products = new javax.swing.JButton();
        btn_Members = new javax.swing.JButton();
        btn_SalesRecords = new javax.swing.JButton();
        btn_Back = new javax.swing.JButton();
        JPanel_RightPanel = new javax.swing.JPanel();
        JPanel_Home = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JPanel_Products = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_price = new javax.swing.JTextField();
        txt_addDate = new javax.swing.JTextField();
        lbl_image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Products = new javax.swing.JTable();
        btn_Insert = new javax.swing.JButton();
        btn_ChooseImage = new javax.swing.JButton();
        btn_Update = new javax.swing.JButton();
        btn_Remove = new javax.swing.JButton();
        btn_First = new javax.swing.JButton();
        btn_Previous = new javax.swing.JButton();
        btn_Next = new javax.swing.JButton();
        btn_Last = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_ClearFields = new javax.swing.JButton();
        btn_RefreshTable = new javax.swing.JButton();
        btn_searchProduct = new javax.swing.JButton();
        JPanel_Members = new javax.swing.JPanel();
        txt_mbr_id = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_mbr_name = new javax.swing.JTextField();
        txt_mbr_lastName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        radio_Female = new javax.swing.JRadioButton();
        radio_Male = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        btn_mbr_Dismiss = new javax.swing.JButton();
        btn_mbr_Employ = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Members = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel_sideBar.setLayout(new java.awt.CardLayout());

        JPanel_Basics.setBackground(new java.awt.Color(254, 254, 254));
        JPanel_Basics.setLayout(new java.awt.GridLayout(12, 0));

        btn_Guides.setText("Guides");
        JPanel_Basics.add(btn_Guides);

        btn_Operations.setText("Operations");
        btn_Operations.setMaximumSize(new java.awt.Dimension(100, 32));
        btn_Operations.setMinimumSize(new java.awt.Dimension(100, 32));
        btn_Operations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OperationsActionPerformed(evt);
            }
        });
        JPanel_Basics.add(btn_Operations);

        btn_Reports.setText("Reports");
        btn_Reports.setMaximumSize(new java.awt.Dimension(100, 32));
        btn_Reports.setMinimumSize(new java.awt.Dimension(100, 32));
        JPanel_Basics.add(btn_Reports);

        btn_About.setText("About");
        btn_About.setMaximumSize(new java.awt.Dimension(100, 32));
        btn_About.setMinimumSize(new java.awt.Dimension(100, 32));
        JPanel_Basics.add(btn_About);

        JPanel_sideBar.add(JPanel_Basics, "card2");

        JPanel_Operations.setBackground(new java.awt.Color(254, 254, 254));
        JPanel_Operations.setLayout(new java.awt.GridLayout(12, 0));

        btn_Products.setText("Products");
        btn_Products.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ProductsActionPerformed(evt);
            }
        });
        JPanel_Operations.add(btn_Products);

        btn_Members.setText("Members");
        btn_Members.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MembersActionPerformed(evt);
            }
        });
        JPanel_Operations.add(btn_Members);

        btn_SalesRecords.setText("Sales Records");
        JPanel_Operations.add(btn_SalesRecords);

        btn_Back.setText("<- Back");
        btn_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BackActionPerformed(evt);
            }
        });
        JPanel_Operations.add(btn_Back);

        JPanel_sideBar.add(JPanel_Operations, "card3");

        jSplitPane1.setLeftComponent(JPanel_sideBar);

        JPanel_RightPanel.setLayout(new java.awt.CardLayout());

        JPanel_Home.setBackground(new java.awt.Color(254, 254, 254));
        JPanel_Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Home Page");
        JPanel_Home.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 240, 80));

        jLabel8.setFont(new java.awt.Font("Consolas", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(1, 1, 1));
        jLabel8.setText("Welcome to ProductControl App!");
        JPanel_Home.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 810, 80));

        JPanel_RightPanel.add(JPanel_Home, "card3");

        JPanel_Products.setBackground(java.awt.Color.white);

        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("ID:");

        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Name:");

        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Price:");

        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Add Date:");

        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("Image:");

        txt_id.setBackground(java.awt.Color.white);
        txt_id.setOpaque(false);
        txt_id.setPreferredSize(new java.awt.Dimension(15, 50));

        txt_name.setOpaque(false);
        txt_name.setPreferredSize(new java.awt.Dimension(15, 50));

        txt_price.setOpaque(false);
        txt_price.setPreferredSize(new java.awt.Dimension(15, 50));

        txt_addDate.setText("yyyy/MM/dd");
        txt_addDate.setOpaque(false);
        txt_addDate.setPreferredSize(new java.awt.Dimension(15, 50));

        lbl_image.setBackground(new java.awt.Color(230, 230, 230));
        lbl_image.setForeground(new java.awt.Color(1, 1, 1));
        lbl_image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_image.setText("No image yet");
        lbl_image.setToolTipText("");
        lbl_image.setOpaque(true);

        table_Products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Add Date"
            }
        ));
        table_Products.setOpaque(false);
        table_Products.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_ProductsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_Products);

        btn_Insert.setBackground(new java.awt.Color(193, 193, 193));
        btn_Insert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/add-smaller.png"))); // NOI18N
        btn_Insert.setText("Insert");
        btn_Insert.setIconTextGap(5);
        btn_Insert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_InsertActionPerformed(evt);
            }
        });

        btn_ChooseImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/download-smaller.png"))); // NOI18N
        btn_ChooseImage.setText("Add Image");
        btn_ChooseImage.setIconTextGap(10);
        btn_ChooseImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChooseImageActionPerformed(evt);
            }
        });

        btn_Update.setBackground(new java.awt.Color(193, 193, 193));
        btn_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/reload-smaller.png"))); // NOI18N
        btn_Update.setText("Update");
        btn_Update.setIconTextGap(5);
        btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpdateActionPerformed(evt);
            }
        });

        btn_Remove.setBackground(new java.awt.Color(193, 193, 193));
        btn_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/criss-cross-smaller.png"))); // NOI18N
        btn_Remove.setText("Remove");
        btn_Remove.setIconTextGap(5);
        btn_Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RemoveActionPerformed(evt);
            }
        });

        btn_First.setBackground(new java.awt.Color(193, 193, 193));
        btn_First.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/left-arrow.png"))); // NOI18N
        btn_First.setText("First");
        btn_First.setIconTextGap(5);
        btn_First.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_FirstActionPerformed(evt);
            }
        });

        btn_Previous.setBackground(new java.awt.Color(193, 193, 193));
        btn_Previous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/previous.png"))); // NOI18N
        btn_Previous.setText("Previous");
        btn_Previous.setIconTextGap(5);
        btn_Previous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PreviousActionPerformed(evt);
            }
        });

        btn_Next.setBackground(new java.awt.Color(193, 193, 193));
        btn_Next.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/next.png"))); // NOI18N
        btn_Next.setText("Next");
        btn_Next.setIconTextGap(5);
        btn_Next.setMaximumSize(new java.awt.Dimension(104, 38));
        btn_Next.setMinimumSize(new java.awt.Dimension(104, 38));
        btn_Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NextActionPerformed(evt);
            }
        });

        btn_Last.setBackground(new java.awt.Color(193, 193, 193));
        btn_Last.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/right-arrow.png"))); // NOI18N
        btn_Last.setText("Last");
        btn_Last.setIconTextGap(5);
        btn_Last.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LastActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("$");

        btn_ClearFields.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/eraser.png"))); // NOI18N
        btn_ClearFields.setText("Clear Fields");
        btn_ClearFields.setIconTextGap(5);
        btn_ClearFields.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClearFieldsActionPerformed(evt);
            }
        });

        btn_RefreshTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/refresh.png"))); // NOI18N
        btn_RefreshTable.setText("Refresh Table");
        btn_RefreshTable.setIconTextGap(5);
        btn_RefreshTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_RefreshTableActionPerformed(evt);
            }
        });

        btn_searchProduct.setBackground(new java.awt.Color(193, 193, 193));
        btn_searchProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/add-smaller.png"))); // NOI18N
        btn_searchProduct.setText("Search");
        btn_searchProduct.setIconTextGap(5);
        btn_searchProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchProductActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanel_ProductsLayout = new javax.swing.GroupLayout(JPanel_Products);
        JPanel_Products.setLayout(JPanel_ProductsLayout);
        JPanel_ProductsLayout.setHorizontalGroup(
            JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_ProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                        .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_addDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_ProductsLayout.createSequentialGroup()
                                .addComponent(txt_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_ProductsLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btn_ChooseImage))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanel_ProductsLayout.createSequentialGroup()
                                .addComponent(txt_id, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_searchProduct))))
                    .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                                .addComponent(btn_Insert)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Update)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_Remove))
                            .addComponent(btn_ClearFields, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                        .addComponent(btn_RefreshTable)
                        .addGap(51, 51, 51)
                        .addComponent(btn_First)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Previous)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Last))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        JPanel_ProductsLayout.setVerticalGroup(
            JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                        .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn_searchProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txt_name, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txt_price, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                                .addComponent(txt_addDate, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(btn_ChooseImage, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_image, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_Insert)
                            .addComponent(btn_Update)
                            .addComponent(btn_Remove)
                            .addComponent(btn_RefreshTable))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ClearFields))
                    .addGroup(JPanel_ProductsLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(JPanel_ProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_First)
                            .addComponent(btn_Previous)
                            .addComponent(btn_Next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_Last))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JPanel_RightPanel.add(JPanel_Products, "card2");

        JPanel_Members.setBackground(new java.awt.Color(254, 254, 254));
        JPanel_Members.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_mbr_id.setBackground(java.awt.Color.white);
        txt_mbr_id.setOpaque(false);
        txt_mbr_id.setPreferredSize(new java.awt.Dimension(15, 50));
        JPanel_Members.add(txt_mbr_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 200, 30));

        jLabel9.setForeground(new java.awt.Color(1, 1, 1));
        jLabel9.setText("ID:");
        JPanel_Members.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel10.setForeground(new java.awt.Color(1, 1, 1));
        jLabel10.setText("Name:");
        JPanel_Members.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txt_mbr_name.setOpaque(false);
        txt_mbr_name.setPreferredSize(new java.awt.Dimension(15, 50));
        JPanel_Members.add(txt_mbr_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 200, 30));

        txt_mbr_lastName.setOpaque(false);
        txt_mbr_lastName.setPreferredSize(new java.awt.Dimension(15, 50));
        JPanel_Members.add(txt_mbr_lastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 200, 30));

        jLabel11.setForeground(new java.awt.Color(1, 1, 1));
        jLabel11.setText(" Sex :");
        JPanel_Members.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        radio_Female.setForeground(new java.awt.Color(1, 1, 1));
        radio_Female.setText("Female");
        JPanel_Members.add(radio_Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        radio_Male.setForeground(new java.awt.Color(1, 1, 1));
        radio_Male.setText("Male");
        JPanel_Members.add(radio_Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        jLabel12.setForeground(new java.awt.Color(1, 1, 1));
        jLabel12.setText("Last Name:");
        JPanel_Members.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        btn_mbr_Dismiss.setBackground(new java.awt.Color(193, 193, 193));
        btn_mbr_Dismiss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/criss-cross-smaller.png"))); // NOI18N
        btn_mbr_Dismiss.setText("Dissmis");
        btn_mbr_Dismiss.setIconTextGap(5);
        btn_mbr_Dismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mbr_DismissActionPerformed(evt);
            }
        });
        JPanel_Members.add(btn_mbr_Dismiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));

        btn_mbr_Employ.setBackground(new java.awt.Color(193, 193, 193));
        btn_mbr_Employ.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/scaled/add-smaller.png"))); // NOI18N
        btn_mbr_Employ.setText("Employ");
        btn_mbr_Employ.setIconTextGap(5);
        btn_mbr_Employ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mbr_EmployActionPerformed(evt);
            }
        });
        JPanel_Members.add(btn_mbr_Employ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        table_Members.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Last Name", "Sex"
            }
        ));
        table_Members.setOpaque(false);
        table_Members.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_MembersMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_Members);

        JPanel_Members.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 580, 440));

        JPanel_RightPanel.add(JPanel_Members, "card4");

        jSplitPane1.setRightComponent(JPanel_RightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ClearFieldsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClearFieldsActionPerformed
        /*** Just clears the fields. ***/
        txt_id.setText("");
        txt_name.setText("");
        txt_price.setText("");
        txt_addDate.setText("");
        lbl_image.setIcon(null);
        lbl_image.setText("...No image yet...");
    }//GEN-LAST:event_btn_ClearFieldsActionPerformed

    private void btn_LastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LastActionPerformed
        /*** shows the latest element in the table of the database. ***/
        this.position = table_Products.getRowCount() - 1;
        // select the row where the user is on right now.
        table_Products.setRowSelectionInterval(this.position, this.position);
        this.showProductItem(this.position);
    }//GEN-LAST:event_btn_LastActionPerformed

    private void btn_NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NextActionPerformed
        /*** Shows the user the next row of the table. ***/
        this.position = (this.position < table_Products.getRowCount() - 1)? this.position + 1 : 0;
        // select the row where the user is on right now.
        table_Products.setRowSelectionInterval(this.position, this.position);
        showProductItem(this.position);
    }//GEN-LAST:event_btn_NextActionPerformed

    private void btn_PreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PreviousActionPerformed
        /*** Shows the user the previous row of the table. ***/
        this.position = (this.position > 0)? this.position - 1 : table_Products.getRowCount() - 1;
        // select the row where the user is on right now.
        table_Products.setRowSelectionInterval(this.position, this.position);
        showProductItem(this.position);
    }//GEN-LAST:event_btn_PreviousActionPerformed

    private void btn_FirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_FirstActionPerformed
        /*** shows the first element in the table of the database. ***/
        this.position = 0;
        // select the row where the user is on right now.
        table_Products.setRowSelectionInterval(this.position, this.position);
        this.showProductItem(this.position);
    }//GEN-LAST:event_btn_FirstActionPerformed

    private void btn_RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RemoveActionPerformed
        /*** Removes an entry from the database, if any. ***/

        // check the correctness of the "ID" field.
        if (!isIDCorrect(txt_id)) return;
        String id = txt_id.getText();

        // get a connection with the database.
        Connection con = getConnection();

        try {
            String query = "DELETE FROM products WHERE id = ?";
            PreparedStatement ps = con.prepareStatement(query);

            try {
                // the the id.
                ps.setInt(1, Integer.parseInt(id));
                // execute the query.
                ps.executeUpdate();

                // show the changes in the jtable.
                showProductsList();

                // confirm success.
                JOptionPane.showMessageDialog(null, "The entry with id = " + id + " has been successfully removed.");
            }
            finally {
                // close the statement.
                try {ps.close();} catch (SQLException ex) {}
            }
        }
        catch (Exception ex) {
            // catch exception of the prepared statement connection.
            JOptionPane.showMessageDialog(null, ex);
        }
        finally {
            // close the database connection.
            try {con.close();} catch (SQLException ex) {}
        }
    }//GEN-LAST:event_btn_RemoveActionPerformed

    private void btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpdateActionPerformed
        /*** The Update button work implementation. ***/

        if (!isIDCorrect(txt_id)) return;

        String id = txt_id.getText();

        String query = "UPDATE products SET name = ?, price = ?, add_date = ?, image = ? WHERE id = " + id;
        boolean success = this.processQuery(query);
        // show the changes in the jtable.
        showProductsList();
        // confirm success.
        if (success) JOptionPane.showMessageDialog(null, "The data has been successfully updated!");
    }//GEN-LAST:event_btn_UpdateActionPerformed

    private void btn_ChooseImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChooseImageActionPerformed
        /*** allows to choose an image using the file chooser and sets the image as an icon into the lbl_image label. ***/

        // set the primordial directory as user/home.
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));

        // allow to use the jpg and png formats only.
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg", "png");
        file.addChoosableFileFilter(filter);

        // get the result of the user has chosen an image.
        int result = file.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            // if so, get the selected file.
            File selectedFile = file.getSelectedFile();
            // get the absolute path of the selected file.
            String path = this.imgPath = selectedFile.getAbsolutePath();
            // clear the label text.
            lbl_image.setText("");
            // set the image as an icon of the lbl_image.label.
            lbl_image.setIcon(resizeImg(path, null));
        }
        // if the user has not chosen an image.
        else {
            // then we just print the message that says "No File Selected".
            System.out.println("No File Selected");
        }
    }//GEN-LAST:event_btn_ChooseImageActionPerformed

    private void btn_InsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_InsertActionPerformed
        // prepare the statement.
        String query = "INSERT INTO products (name, price, add_date, image) VALUES (?, ?, ?, ?)";
        boolean success = this.processQuery(query);
        if (success) JOptionPane.showMessageDialog(null, "The data has been successfully added!");
    }//GEN-LAST:event_btn_InsertActionPerformed

    private void table_ProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_ProductsMouseClicked
        this.position = table_Products.getSelectedRow();
        this.showProductItem(this.position);
    }//GEN-LAST:event_table_ProductsMouseClicked

    private void btn_RefreshTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_RefreshTableActionPerformed
        /*** Refreshes the table of data. ***/
        this.showProductsList();
    }//GEN-LAST:event_btn_RefreshTableActionPerformed

    private void btn_OperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OperationsActionPerformed
        JPanel_sideBar.removeAll();
        JPanel_sideBar.add(JPanel_Operations);
        JPanel_sideBar.repaint();
        JPanel_sideBar.revalidate();
    }//GEN-LAST:event_btn_OperationsActionPerformed

    private void btn_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BackActionPerformed
        JPanel_sideBar.removeAll();
        JPanel_sideBar.add(JPanel_Basics);
        JPanel_sideBar.repaint();
        JPanel_sideBar.revalidate();
    }//GEN-LAST:event_btn_BackActionPerformed

    private void btn_ProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ProductsActionPerformed
        JPanel_RightPanel.removeAll();
        JPanel_RightPanel.add(JPanel_Products);
        JPanel_RightPanel.repaint();
        JPanel_RightPanel.revalidate();
        
        // show data of products in the jtable.
        this.showProductsList();
    }//GEN-LAST:event_btn_ProductsActionPerformed

    private void btn_mbr_DismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mbr_DismissActionPerformed
        if (!isIDCorrect(txt_mbr_id)) return;
        String id = txt_mbr_id.getText();
        
        Connection con = this.getConnection();
        
        try {
            String query = "DELETE FROM members WHERE id = ?";
            PreparedStatement ps = con.prepareStatement(query);
            
            try {
                // set the dismissing member id.
                ps.setString(1, id);
                
                // execute the query.
                ps.executeUpdate();
                
                // update data in the jtable of members.
                this.showMembersList();
                
                // confirm success of the deletion.
                JOptionPane.showMessageDialog(null, "The member with id = " + id + " has been successfully dismissed.");
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Couldn't execute the query!");
                System.out.println(ex);
            }
            finally {
                try {ps.close();} catch (SQLException ex) {}
            }
        }
        catch (SQLException ex) {
            // catch exception of the prepared statement connection.
            JOptionPane.showMessageDialog(null, "Some problems have appeared while preparing the statement!");
        }
        finally {
            try {con.close();} catch (SQLException ex) {}
        }
    }//GEN-LAST:event_btn_mbr_DismissActionPerformed

    private void btn_mbr_EmployActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mbr_EmployActionPerformed
        if (this.checkMbrsInputs()) {
            
            // get a connection with the database.
            Connection con = this.getConnection();
            
            try {
                String query = "INSERT INTO members (name, last_name, sex) VALUES (?, ?, ?)";
                PreparedStatement ps = con.prepareStatement(query);
                
                try {
                    // set the name of the new member.
                    ps.setString(1, txt_mbr_name.getText());
                    // set the last name of the new member.
                    ps.setString(2, txt_mbr_lastName.getText());
                    // set the sex of the new member.
                    ps.setString(3, this.getRadioSelectedText());
                    
                    // execute the query.
                    ps.executeUpdate();
                    
                    // update data in the jtable of members.
                    this.showMembersList();
                    
                    // confirm success.
                    JOptionPane.showMessageDialog(null, "The new member has been successfully added!");
                }
                catch (SQLException ex) {
                    JOptionPane.showMessageDialog(null, "Couldn't execute the query!");
                    System.out.println(ex);
                }
                finally {
                    // close the connection of the prepared statement.
                    try {ps.close();} catch (SQLException ex) {}
                }
            }
            catch (Exception ex) {
                // catch exception of the prepared statement connection.
                JOptionPane.showMessageDialog(null, "Some problems have appeared while preparing the statement!");
            }
            finally {
                // close the connection.
                try {con.close();} catch (SQLException ex) {}
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "One or more fields are empty!");
        }
    }//GEN-LAST:event_btn_mbr_EmployActionPerformed

    private String getRadioSelectedText() {
        /*** Returns the text of the selected radio button in the ButtonGroup. ***/
        for (Enumeration btns = bg.getElements(); btns.hasMoreElements();) {
            AbstractButton button = (AbstractButton) btns.nextElement();
            
            if (button.isSelected()) return button.getText();
        }
        return null;
    }
    
    private void table_MembersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_MembersMouseClicked
        /*** shows a member information by clicking a row. ***/
        
        // get the index of the selected row.
        int index = table_Members.getSelectedRow();
        this.showMemberItem(index);
    }//GEN-LAST:event_table_MembersMouseClicked

    private void btn_MembersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MembersActionPerformed
        JPanel_RightPanel.removeAll();
        JPanel_RightPanel.add(JPanel_Members);
        JPanel_RightPanel.repaint();
        JPanel_RightPanel.revalidate();
        
        // show data in the jtable.
        this.showMembersList();
    }//GEN-LAST:event_btn_MembersActionPerformed

    private void btn_searchProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchProductActionPerformed
        /*** Returns a product by its ID. ***/
        
        // get the ID from its field if it's correct.
        if (!this.isIDCorrect(txt_id)) return;
        int id = Integer.parseInt(txt_id.getText());
        
        ArrayList<Product> products = this.getProductsList();
        for (int i = 0, len = products.size(); i < len; i++) {
            // if we find the nessesary product.
            if (products.get(i).getId() == id) {
                // then we show its full information ...
                this.showProductItem(i);
                // ... and immediately break the cycle.
                return;
            }
        }
        // if there is no product with the id we confirm the user about it.
        JOptionPane.showMessageDialog(null, "There is no product with the ID = " + id + "!");
    }//GEN-LAST:event_btn_searchProductActionPerformed
    
    private boolean processQuery(String query) {
        /*** processes a query to the database. 
         * At first, we try to get all connections, streams, etc. and only then
         * we process all the rest operations for the query.
         * The following pattern of nested try-catch-finally statements allows us
         * to keep track of each connection or stream we try to get.
        ***/
        
        boolean success = false;
        
        if (checkOptsInputs() && this.imgPath != null) {
            
            // get a connection with the database.
            Connection con = getConnection();
            
            try {
                PreparedStatement ps = con.prepareStatement(query);
                
                try {
                    // get a stream of the image and set it into the database.
                    InputStream img = new FileInputStream(new File(this.imgPath));
                    
                    try {
                        /* process the query.*/
                        
                        // set the name.
                        ps.setString(1, txt_name.getText());
                        // set the price.
                        ps.setString(2, txt_price.getText());
                        // set the added date.
                        ps.setString(3, txt_addDate.getText());
                        // set the image.
                        ps.setBlob(4, img);
                
                        // execute the query.
                        ps.executeUpdate();
                        
                        // show the jtable with the new row.
                        showProductsList();
                
                        success = true;
                        
                    }
                    finally {
                        // close the stream of img.
                        try {img.close();} catch (Exception ex) {}
                    }
                }
                catch (Exception ex) {
                    // catch an exception of getting the image stream.
                    JOptionPane.showMessageDialog(null, "The image size is too large. Please, choose a smaller image size.\n"
                            + "(The size of the image must be up to 1 Mb!)");
                }
                finally {
                    // close the connection of the prepared statement.
                    try {ps.close();} catch (SQLException ex) {}
                }
            }
            catch (Exception ex) {
                // catch exception of the prepared statement connection.
                JOptionPane.showMessageDialog(null, ex);
            }
            finally {
                // close the connection.
                try {con.close();} finally {return success;}
            }
        }
        else {
            JOptionPane.showMessageDialog(null, "One or more fields are empty!");
        }
        
        return success;
    }
            
    private void showProductItem(int index) {
        /*** fills the fields with an item information depending on the parameter "index". ***/
        
        // get the ArrayList of products.
        Product prItem = getProductsList().get(index);
        
        // set the fields with the indexed item information.
        txt_id.setText(Integer.toString(prItem.getId()));
        txt_name.setText(prItem.getName());
        txt_price.setText(Float.toString(prItem.getPrice()));
        txt_addDate.setText(prItem.getAddDate());
        // clear the "image" label before set a new image.
        lbl_image.setText("");
        lbl_image.setIcon(resizeImg(null, prItem.getImage()));
    }
    
    private void showMemberItem(int index) {
        // get the nessesary member from ArrayList of members.
        Member member = getMembersList().get(index);
        
        // set the field with the member's data.
        txt_mbr_id.setText(Integer.toString(member.getId()));
        txt_mbr_name.setText(member.getName());
        txt_mbr_lastName.setText(member.getLastName());
        
        // get sex of the member.
        String sex = table_Members.getModel().getValueAt(index, 3).toString();
        for (Enumeration btns = bg.getElements(); btns.hasMoreElements();) {
            AbstractButton button = (AbstractButton) btns.nextElement();
            
            if (sex.equals(button.getText())) {
                button.setSelected(true);
                break;
            }
        }
    }
        
    private boolean isIDCorrect(JTextField field) {
        /*** checks if the id is correct. ***/
        
        String id = field.getText();
        
        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(null, "The field \"ID\" must not be empty!");
            return false;
        }
        else {
            try {
                Integer.parseInt(id);
                return true;
            }
            catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Enter the correct ID!");
                return false;
            }
        }
    }
    
    private ArrayList<Product> getProductsList() {
        /*** gets the table of products from the database, stores an instance
         * of each row in an ArrayList and returns the ArrayList.
        ***/
        
        // create an ArrayList that is going to keep products from the database.
        ArrayList<Product> productsList = new ArrayList<Product>();
        
        // get the database connection.
        Connection con = getConnection();
        
        try {
            // use the Statement object just to get data from the database.
            Statement st = con.createStatement();
            
            try {
                // execute the following query and store the result in a ResultSet instance.
                String query = "SELECT * FROM products";
                ResultSet rs = st.executeQuery(query);
                
                // go through the ResultSet instance.
                while (rs.next()) {
                    // store each row of the result set as a Product instance.
                    Product product = new Product(rs.getInt("id"), rs.getString("name"),
                            Float.parseFloat(rs.getString("price")), rs.getString("add_date"),
                            rs.getBytes("image"));
                    // add the instance of each row into the created ArrayList.
                    productsList.add(product);
                }
                
                // close the execution.
                try {rs.close();} catch (SQLException ex) {}
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Couldn't show products into the table.!");
                System.out.println(ex);
            }
            finally {
                // close the statement.
                try {st.close();} catch (SQLException ex) {}
            }
        }
        catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Some problems have appeared.");
            System.out.println(ex);
        }
        finally {
            // close the database connection.
            try {con.close();} catch (SQLException ex) {}
        }
        
        return productsList;
    }
    
    private ArrayList<Member> getMembersList() {
        /*** Return members list. ***/
        
        ArrayList<Member> membersList = new ArrayList<Member>();
        Connection con = this.getConnection();
        
        try {
            Statement st = con.createStatement();
            
            try {
                // get the table with members.
                String query = "SELECT * FROM members";
                ResultSet members = st.executeQuery(query);
                
                // go through the ResultSet instance.
                while (members.next()) {
                    // create an object of the current member.
                    Member member = new Member(members.getInt("id"), members.getString("name"),
                        members.getString("last_name"), members.getString("Sex"));
                    
                    // store the gotten member into the created ArrayList.
                    membersList.add(member);
                }
                
                // close the execution.
                try {members.close();} catch (SQLException ex) {}
            }
            catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Couldn't show members into the table!");
                System.out.println(ex);
            }
            finally {
                try {st.close();} catch (SQLException ex) {}
            }
            
        }
        catch (SQLException ex) {
            // catch "Statement st = con.createStatement()".
            JOptionPane.showMessageDialog(null, "Some problems have appeared.");
            System.out.println(ex);
        }
        finally {
            try {con.close();} catch (SQLException ex) {}
        }
        
        // return the gotten member list as a result.
        return membersList;
    }
    
    private void showProductsList() {
        /*** The behavior of the function follows from the function name. ***/
        
        // get the ArrayList of products from the database.
        ArrayList<Product> productsList = this.getProductsList();
        // create a model of the table that we will populate the data in.
        DefaultTableModel model = (DefaultTableModel) table_Products.getModel();
        // clear the jtable before we fill it.
        model.setRowCount(0);
        
        Object[] row = new Object[4];
        // go through the ArrayList of products and add its each element
        // to the model of the table as an array of Objects.
        for (int i = 0, len = productsList.size(); i < len; i++) {
            // get one product.
            Product product = productsList.get(i);
            
            // store the product's data in the temprorary array.
            row[0] = product.getId();
            row[1] = product.getName();
            row[2] = product.getPrice();
            row[3] = product.getAddDate();
            
            // add the prepared row onto the jtable of products.
            model.addRow(row);
        }
    }
    
    private void showMembersList() {
        /*** Populates the "table_Members" table with members. ***/
        
        // get the members list.
        ArrayList<Member> membersList = getMembersList();
        // get the model of the jtable we'll populate with the members' data.
        DefaultTableModel model = (DefaultTableModel) table_Members.getModel();
        // clear the jtable of members before we fill it.
        model.setRowCount(0);
        
        // a temprorary array that keeps data of one member in the order according
        // the order of the table columns of one row.
        Object[] row = new Object[4];
        for (int i = 0, len = membersList.size(); i < len; i++) {
            // get one member.
            Member member = membersList.get(i);
            
            // store the member's data in the temrorary array.
            row[0] = member.getId();
            row[1] = member.getName();
            row[2] = member.getLastName();
            row[3] = member.getSex();
            
            // add the prepared row onto the jtable of products.
            model.addRow(row);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Window.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Window().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel_Basics;
    private javax.swing.JPanel JPanel_Home;
    private javax.swing.JPanel JPanel_Members;
    private javax.swing.JPanel JPanel_Operations;
    private javax.swing.JPanel JPanel_Products;
    private javax.swing.JPanel JPanel_RightPanel;
    private javax.swing.JPanel JPanel_sideBar;
    private javax.swing.JButton btn_About;
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_ChooseImage;
    private javax.swing.JButton btn_ClearFields;
    private javax.swing.JButton btn_First;
    private javax.swing.JButton btn_Guides;
    private javax.swing.JButton btn_Insert;
    private javax.swing.JButton btn_Last;
    private javax.swing.JButton btn_Members;
    private javax.swing.JButton btn_Next;
    private javax.swing.JButton btn_Operations;
    private javax.swing.JButton btn_Previous;
    private javax.swing.JButton btn_Products;
    private javax.swing.JButton btn_RefreshTable;
    private javax.swing.JButton btn_Remove;
    private javax.swing.JButton btn_Reports;
    private javax.swing.JButton btn_SalesRecords;
    private javax.swing.JButton btn_Update;
    private javax.swing.JButton btn_mbr_Dismiss;
    private javax.swing.JButton btn_mbr_Employ;
    private javax.swing.JButton btn_searchProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lbl_image;
    private javax.swing.JRadioButton radio_Female;
    private javax.swing.JRadioButton radio_Male;
    private javax.swing.JTable table_Members;
    private javax.swing.JTable table_Products;
    private javax.swing.JTextField txt_addDate;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mbr_id;
    private javax.swing.JTextField txt_mbr_lastName;
    private javax.swing.JTextField txt_mbr_name;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_price;
    // End of variables declaration//GEN-END:variables
}
